# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deja < Formula
  desc "Predictive inline shell autosuggestions for zsh."
  homepage "https://github.com/Giammarco-Ferranti/deja"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.2.4/deja_0.2.4_darwin_amd64.tar.gz"
      sha256 "258c037a3e67428d7273439f7ae3ee001f2f9a4a47d2437477d016adb70caeee"

      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.2.4/deja_0.2.4_darwin_arm64.tar.gz"
      sha256 "765850e118eaf010f5e0c52c115f83bee2cd7abba262721ce9bc5fde394ac485"

      define_method(:install) do
        bin.install "deja"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.2.4/deja_0.2.4_linux_amd64.tar.gz"
      sha256 "aafd657be64c476f0cc3d329e6e0e894be406f0bed49b8714fb9782f50ebfeba"
      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.2.4/deja_0.2.4_linux_arm64.tar.gz"
      sha256 "f51565978a3bab5231473c120722cfa082cf07f1343abe2a39b6b2db045d0d7b"
      define_method(:install) do
        bin.install "deja"
      end
    end
  end

  def caveats
    <<~EOS
      To enable deja in zsh, add the following to your ~/.zshrc:

        eval "$(deja init zsh)"

      Import your existing zsh history with:

        deja import
    EOS
  end

  test do
    system "#{bin}/deja", "--help"
  end
end
