# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Deja < Formula
  desc "Predictive inline shell autosuggestions for zsh."
  homepage "https://github.com/Giammarco-Ferranti/deja"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.1.1/deja_0.1.1_darwin_amd64.tar.gz"
      sha256 "b5aa0c83d071ac8af6d0dc6a074bef6c70f7aa75801b796b78a8a38a95dfbb45"

      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.1.1/deja_0.1.1_darwin_arm64.tar.gz"
      sha256 "7c36e7f1e85860e68a5ebc2032b554984d0a7d646bdb1863896d2fc65cae747d"

      define_method(:install) do
        bin.install "deja"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.1.1/deja_0.1.1_linux_amd64.tar.gz"
      sha256 "855dcf1e369ed7048d7cce3ef5814c0bf297667491040405820b436f14336e23"
      define_method(:install) do
        bin.install "deja"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Giammarco-Ferranti/deja/releases/download/v0.1.1/deja_0.1.1_linux_arm64.tar.gz"
      sha256 "0f85aa2abdd4cb3d16298515ba63dda707ff8018b0af6d65a55846dfec1df0b5"
      define_method(:install) do
        bin.install "deja"
      end
    end
  end

  def caveats
    <<~EOS
      To enable deja in zsh, add the following to your ~/.zshrc:

        eval "$(deja init zsh)"

      Import your existing zsh history with:

        deja import
    EOS
  end

  test do
    system "#{bin}/deja", "--help"
  end
end
